[build]
target = "./mns-x64.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.thumbv7em-none-eabihf]
rustflags = ["-C", "link-arg=--allow-multiple-definition"]

